### ISSUE TITLE
Hi, is there a picture to explain the terms in the code ?

### ISSUE THREAD

**Issue by zhangyanwei** [jtextor/cpm#5]
I think the picture should be similar to [this](https://upload.wikimedia.org/wikipedia/commons/thumb/8/81/Prostatehistology.jpg/250px-Prostatehistology.jpg).
if you post it, that would be very helpful !

**Comment by jtextor** [comment]
I do not quite understand this question, sorry. The CPM can simulate very different types of cells, so I believe a picture like the one you link to would very much depend on the actual setting being simulated?

**Comment by zhangyanwei** [comment]
thank you, now I know how to simulate it, after few days learning.
